[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mbstring", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.bcmath", "php83Extensions.gd", "php83Extensions.fileinfo", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "sh start.sh"
